# Generated by Django 2.0.7 on 2018-07-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='attractions',
            field=models.ManyToManyField(to='attraction.Attraction'),
        ),
    ]
