# Generated by Django 2.0.7 on 2018-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('reviews', '0001_initial'),
        ('core', '0002_spot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='spot',
            name='review',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
