# Generated by Django 2.0.7 on 2018-07-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_spot_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='attractions',
            field=models.ManyToManyField(blank=True, null=True, to='attraction.Attraction'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localization.Localization'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='review',
            field=models.ManyToManyField(blank=True, null=True, to='reviews.Review'),
        ),
    ]
